name: test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Test Coverage Report
      run: |
        yarn install --frozen-lockfile
        yarn lint
        yarn test:coverage
    - name: Coveralls
      uses: coverallsapp/github-action@v2
